### PR TITLE
Integrate ESLint and Prettier to the project

### PR DESCRIPTION
**Pull request by mandaputtra**
Turns out there are a lot of files to lint!  

- [x] Configure ESLint and prettier standard style
- [ ] Lint fix all files
- [ ] Install husky as git hooks

### CODE REVIEW

**Comment by mandaputtra** [comment]
I'm having trouble figuring out what this code means

```js
const dataService = require('./data.service')
const helperService = require('./helper.service')
const fileService = require('./file.service')

// var fs = require('fs');

const handlebars = require('handlebars')

module.exports = viewService = {
  getProcessedView: function (contentType, viewModel, viewPath) {
    const source = viewService.getHandlebarsTemplateForContentType(
      contentType,
      viewPath
    )

    const result = viewService.processTemplateString(source, viewModel)

    return result
  },

  processTemplateString: function (template, viewModel) {
    const templateView = handlebars.compile(template)

    const result = templateView(viewModel)

    return result
  },

  getHandlebarsTemplateForContentType: function (contentType, viewPath) {
    const file = fileService.getFileSync(viewPath)
    return file
  }
}
```

Is this a recursive calls?

**Comment by lane711** [comment]
Thanks for starting this PR!

These are not recursive calls but we can reformat that way, that is fine with me

When I checkout this PR, there are a lot of issues loading the formio forms. If you do `npm test` all of the tests crash.

I''m seeing this error in the browser from the admin section:
Uncaught SyntaxError: Identifier 'axiosInstance' has already been declared

**Comment by mandaputtra** [comment]
Hi, Could you help me to understand what are this code doing?, This are on `helper.service.js` it always present on all services files. Is this service registering the function as global object?

```js
// var dataService = require('./data.service');
// var sanitizeHtml = require('sanitize-html');

// var fs = require('fs');
// // const axios = require('axios');
// const ShortcodeTree = require('shortcode-tree').ShortcodeTree;
// const chalk = require('chalk');
// const log = console.log;

// import FormioForm from 'formiojs/form';

// import { Form } from 'formiojs';

// const {f} = require('formiojs');
// var formio = require('formio-service')();
// var Form = formio.Form;

// const utils = require('formiojs/utils');

;(function (exports) {
  if (typeof module !== 'undefined' && module.exports) {
    const helperService = require('./helper.service')
  } else {
    // client version
  }

  ;(exports.truncateString = function (body, length) {
    if (body) {
      const cleanHtml = body.substring(0, 450)
      // if(sanitizeHtml){
      //     cleanHtml = sanitizeHtml(body, {
      //         allowedTags: [],
      //         allowedAttributes: false
      //     });
      // }

      return cleanHtml.length > length
        ? cleanHtml.substr(0, length - 1) + '...'
        : cleanHtml
    }
  }),
    (exports.urlAppendParam = function (url, paramName, paramValue) {
      let baseUrl = url
      if (url.indexOf('?') > -1) {
        baseUrl = url.substring(0, url.indexOf('?'))
      }
      return `${baseUrl}?${paramName}=${paramValue}`
    }),
    (exports.sleep = function (ms) {
      return new Promise((resolve) => {
        setTimeout(resolve, ms)
      })
    }),
    (exports.generateRandomString = function (length) {
      let result = ''
      const characters =
        'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
      const charactersLength = characters.length
      for (let i = 0; i < length; i++) {
        result += characters.charAt(
          Math.floor(Math.random() * charactersLength)
        )
      }
      return result
    }),
    (exports.getCookie = function (name) {
      // debugger;
      if (typeof document !== 'undefined' && document && document.cookie) {
        const value = '; ' + document.cookie
        const parts = value.split('; ' + name + '=')
        if (parts.length == 2) {
          return parts.pop().split(';').shift()
        }
      }
    })
  exports.slugify = function (text) {
    // console.log('slug', text);
    const slug = text
      .toLowerCase()
      .replace(/[^\w ]+/g, '')
      .replace(/ +/g, '-')

    return slug
  }
  exports.validateEmail = function (email) {
    const re =
      /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
    return re.test(String(email).toLowerCase())
  }
  exports.generateSlugFromContent = function (
    content,
    includePrecedingSlash = false,
    makeUnique = false
  ) {
    let copy = content.title
    if (!copy) copy = content.text
    if (!copy) copy = content.body
    if (!copy) copy = content.alertCopy
    if (!copy) copy = content.contentType

    // let copyClean =  formattingService.stripHtmlTags(copy)

    let slug = this ? this.slugify(copy) : slugify(copy)

    if (includePrecedingSlash === true) {
      slug = `/${slug}`
    }

    if (makeUnique === true) {
      slug = `${slug}-${this.generateRandomString(6)}`
    }

    return slug
  }
})(typeof exports === 'undefined' ? (this.helperService = {}) : exports)

```

**Comment by mandaputtra** [comment]
I think it would be hard if I also refactor on this PR, I need to know how the internals work first. I think I'll just integrate the ESLint first and the slowly refactor one by one after that, is that good?

Most of the linters' error are `non-unused-vars` and `no-undef`. 

Screen Shot 2022-02-01 at 15 27 04

**Comment by lane711** [comment]
@mandaputtra the `helper.service.js` file is used both on the back end and front end for some basic utilities. It is loaded in the browser on the front end so in that respect it is global.

**Comment by lane711** [comment]
@mandaputtra yes probably better to just integrate and we can slowly fix all the issues over time. Thanks again for taking this on!

**Comment by mandaputtra** [comment]
No worries, because ir will also help another contributors 💯 I'll close this and do it on another PR

**Pull request closed without merging**
