### PR TITLE
Npx command

### LINKED ISSUE #189: Create a npx command for new project
This will replace the current getting started instructions, making it easier for developers to quick 

This will replace:
https://sonicjs.com/getting-started

### PR DESCRIPTION
**Pull request by lukasbe**
My take for an npx command to bootstrap a sonicjs project.

Usage similar to create react app.

```npx sonicjs ${dirToClone}```

dirToClone defaults to ```sonicjs```, so it is also possible to call ```npx sonicjs``` and the project will be checked out to a dir called ```sonicjs```

optionally, the cloudflare parameters can be passed in, if they are omitted, users are prompted to input them via a cli prompt.

To pass the parameters directly the following can be called:
```npx sonicjs ${dirToClone} ${cloudflareAccountId} ${cloudflareKvNamespaceId} ${cloudflareKvNamespacePreviewId} ${cloudflareDatabaseId}```

Parameters can be omitted, but for now the order has to be kept.

The script is placed in .scripts/generate.mjs.

resolves #189

### CODE REVIEW

**Comment by lukasbe** [comment]
currently there is an npx bug that prevents users from calling npx scripts from github directly via the npx shorthand.

The full ```npm exec ...``` command has to be used if the package is not published on npm.

**Comment by lukasbe** [comment]
see also Comments here: https://dev.to/ipreda/run-your-npx-script-directly-from-github-create-your-own-cli-commands-and-other-stories-4pn3

It seems that it is related to how parameters are evaluated in npx vs npm exec: https://docs.npmjs.com/cli/v9/commands/npm-exec?v=true#npx-vs-npm-exec

But as it is written in the article's comment section, after executing ```npm exec github:...``` once, also ```npx github:...``` works for me.

**Comment by lane711** [comment]
@lukasbe this works great! I went ahead and merged it in order to test it out. There are a couple of really minor updates I'd like to request:

1. change "please" to "Please"
2. on line 96, you can remove the instructions to run `npm install` since its already done for you on line 67

**Comment by lukasbe** [comment]
You're right, thank you so much for your review. I opened a new pull request: #193

**Pull request merged**
