### PR TITLE
style: apply prettier

### PR DESCRIPTION
**Pull request by totto2727**
# Summary

Continued from https://github.com/lane711/sonicjs/pull/237

Currently, the number of PRs is relatively small, and this is an opportunity to apply them collectively.

# Concerns.

Ongoing tasks need to Rebase or Merge. Conflicts are likely to occur and will require a certain time cost to resolve.

It is also possible that a large number of conflicts may occur due to forking of other working contributors.

The project should be formatted as soon as possible, but we would like to ask for your judgment because of the risks mentioned above.

# Countermeasures

After a quick check, `"trailingComma": "es5"` and `"singleQuote": true` may be needed.

Introducing these may reduce the differences.

### CODE REVIEW

**Comment by lane711** [comment]
Thank  you again for your PR and for helping us cleanup the formatting

1. can you please remove the trailing comma at the end of objects?
2. please change  double quotes to single quotes

**Comment by totto2727** [comment]
Fixed!
What do you think?

If you prefer double quotation marks for CSS, etc., I will adjust it.

**Comment by totto2727** [comment]
Fixed GitHub Actions triggers.
Fork-derived PRs will also fire.

**Comment by lane711** [comment]
yes we probably need to use double quotes for CSS. That seems to be most common

**Comment by totto2727** [comment]
I understand.
Use the Override function to double-quote only CSS.

https://prettier.io/docs/en/configuration.html#configuration-overrides

```js
 "overrides": [
   {
     "files": ["*.css"],
     "options": {
       singleQuote: false,
     }
   }
 ]
```

**Pull request merged**
