### PR TITLE
Dynamic Database Schema

### PR DESCRIPTION
**Pull request by rhamses**
This PR added the functionality to create any sqlite db schema you want while the admin CRUD screens and the APIs endpoints updates accordingly. So now every time a new schema is created, the only file needs to updated is the `/db/routes.ts` besides the schema itself. 

These changes objectives are:
- The `/db/schema` folder now supports the [Drizzle separate files definition](https://orm.drizzle.team/docs/sql-schema-declaration) so each table can be defined separately from each other. 
- The `schema.ts` file is renamed to `routes.ts` in order to avoid confusion with the new `schema` folder and also to trying to define better the goal of this file. 
- A new folder called `/db/definitions` is created to hold general information about the tables, mainly: table name, route, and the structure of the schema. 
- The `/db/routes.ts` file is responsible to import all table schemas from `/db/schemas` folder and creating two new exports objects called: `tableDefinitions` and `tableSchemas` which will be used across the project.

### CODE REVIEW

**Comment by rhamses** [comment]
Hey @lane711 here's the PR we've talked about. I hope it's clear the intent but I'd love to get your perspective on it, specially because I change quite a lot files. Also, after I've been using for the past couple weeks I realize it has room to grow and optimize but I hope this version is already ok.

**Comment by lane711** [comment]
Wow, thanks for taking this on. It looks like a big improvement at first glance. Let me dig in tomorrow and get back to you. Thanks!

**Comment by lane711** [comment]
Hey @rhamses I just checked this out, ran locally and it looks great - a big improvement! 

I did notice that there are 3 tests failing. Are you getting that locally as well? I usually run `jest` and then `jest --onlyFailures`:

Screenshot 2023-11-17 at 2 57 00 PM

**Comment by rhamses** [comment]
Hi @lane711 I think I didn’t catch these ones. I’ll take a look this weekend to see why they are failing and will correct it

**Comment by rhamses** [comment]
> Hi @lane711 I think I didn’t catch these ones. I’ll take a look this weekend to see why they are failing and will correct it

Just to circle back on this. I'm having trouble with the setup of the test. I'll take more time to understand exactly what it happens and then update the code.

**Comment by rhamses** [comment]
@lane711 I updated the code with [this commit](https://github.com/lane711/sonicjs/pull/216/commits/79ce4d76ce7e28ea37db965fa1eb9fbe752cf578). The test made me think a little bit and I optimize the schema folder and functions so It would be easy to maintain down the road. Please, tell me what you think. Cheers!

**Comment by lane711** [comment]
@rhamses thank you for fixing the failing tests. It looks like the tests are technically passing but throwing errors, so I now see this when I run `jest`:

Screenshot 2023-12-01 at 5 56 04 PM

**Comment by lane711** [comment]
hey @rhamses I was able to fix the failing tests and all looks good now. Thanks again for your work. This is a major improvement. I'll update the docs accordingly in the next couple of days

**Pull request merged**
