### PR TITLE
File/Image uploading to R2

### PR DESCRIPTION
**Pull request by acoreyj**
This builds on the auth branch as it adds some more to the table config stuff.

I haven't written any docs and might be a while before I get back to it.

Basically you set some field config by exporting the variable fields from one of your route schemas. That field config should have the field name as the key, type of "file", a key "bucket" which is a function that takes in the AppContext and returns your bucket. And optionally a path that is added on to where the file is stored in r2.
Can look at src/db/schema/posts.ts for an example.

```ts
export const fields: ApiConfig["fields"] = {
  image: {
    type: "file",
    bucket: (ctx) => ctx.env.R2_STORAGE,
    path: "images",
  },
};
```
Obviously need to bind the R2 in wrangler.toml or cloudflare config

```toml
[[r2_buckets]]
binding = 'R2_STORAGE' 
bucket_name = ''
```

There are a couple things that can probably be improved like the added complexity in form-content.js. Adding/removing the formio fields is a bit wonky, how it stores/figures out the field and table as part of the path is a bit odd, Uppy is loaded from a CDN which is heavier than it needs to be. 

Not 100% sure on what changes I would make though and probably won't get back to it for a bit. 

image
image
image

### CODE REVIEW

**Comment by rhamses** [comment]
Really cool! I'll be looking into it because I'm in need to do something like this as well. ([I actually built before look for PRs](https://github.com/rhamses/sonicjs/tree/feature/r2))

Does your version provide functions to be used outside the admin layout? Like the `insertRecords` / `getRecords` ?

**Comment by acoreyj** [comment]
> Really cool! I'll be looking into it because I'm in need to do something like this as well. ([I actually built before look for PRs](https://github.com/rhamses/sonicjs/tree/feature/r2))
> 
> Does your version provide functions to be used outside the admin layout? Like the `insertRecords` / `getRecords` ?

It doesn't really yet, it creates a tus API (tus.io) so I can document what it's expecting or add some endpoints.

**Comment by lane711** [comment]
Hey @acoreyj thanks for your work on this. I started to review this but it looks like the new migrations do  not build on the existing migrations so I am getting errors like "table `categories` already exists at offset 13"

**Comment by lane711** [comment]
hey @acoreyj I got this running locally and it  works great! Is this ready to be merged aside from the migrations issue?

**Comment by acoreyj** [comment]
@lane711 

I believe I just fixed the migration issue, yup it's ready to be merged

**Pull request merged**
